version: '3.8'

services:
  sqlapp:
    image: mysql:8.0.39-oraclelinux9
    environment:
      MYSQL_ROOT_PASSWORD: "Cuador.0730"
      MYSQL_DATABASE: "epolaris"
      MYSQL_USER: "adminnet"
      MYSQL_PASSWORD: "Cuador.0730"
    ports:
      - "3306:3306"
    volumes:
      - ./init-user.sql:/docker-entrypoint-initdb.d/init-user.sql

  nodeapp:
    build:
      context: .
    ports:
      - "443:443"
    depends_on:
      - sqlapp
  telegraf:
    image: telegraf:1.18-alpine
    restart: always
    volumes:
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125'

  influxdb:
    image: influxdb:1.8-alpine
    restart: always
    env_file: configuration.env
    ports:
      - '8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:8.0.2
    restart: always    
    depends_on:
      - influxdb
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/

volumes:
  grafana_data: {}
  influxdb_data: {}

